// Generated by LiveScript 1.2.0
(function(){
  window.getMouse = function(el){
    var mouse;
    mouse = {
      x: 0,
      y: 0
    };
    el.onmousemove = function(e){
      mouse.x = e.layerX;
      return mouse.y = e.layerY;
    };
    return mouse;
  };
  window.getKeys = function(){
    var keys;
    keys = {
      up: false,
      down: false,
      left: false,
      right: false
    };
    document.addEventListener('keydown', function(e){
      switch (e.which) {
      case 37:
      case 65:
        keys.left = true;
        return keys.right = false;
      case 38:
      case 87:
        keys.up = true;
        return keys.down = false;
      case 39:
      case 68:
        keys.right = true;
        return keys.left = false;
      case 40:
      case 83:
        keys.down = true;
        return keys.up = false;
      }
    });
    document.addEventListener('keyup', function(e){
      switch (e.which) {
      case 37:
      case 65:
        return keys.left = false;
      case 38:
      case 87:
        return keys.up = false;
      case 39:
      case 68:
        return keys.right = false;
      case 40:
      case 83:
        return keys.down = false;
      }
    });
    return keys;
  };
}).call(this);
